### PR TITLE
problem: discussion doesn't work

### LINKED ISSUE #18: problem: discussion doesn't work
`/rockets/merits/[id]`

The discussion area is not implemented.

solution:
Create a discussion component to render notes that are in reply to merit requests etc (and also publish new comments)

### PR DESCRIPTION
**Pull request by bob2402**
resolve #18 

Time spent: 1 hour and 40 minutes

### CODE REVIEW

File: src/components/MeritComment.svelte [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+		if (!ndk.signer) {
+			throw new Error('no ndk signer found');
+		}
+		let e = new NDKEvent(ndk);
+		let author = $currentUser;
+		if (!author) {
+			throw new Error('no current user');
+		}
+		e.author = author;
+		e.kind = 1;
```
Comment (bob2402) [inline src/components/MeritComment.svelte:37]: I did not see the need for a new kind to be used for merit discuss in NIP, so I used the generic kind 1 here.
